/**
 * Sample dataset for the playground: a produce catalog.
 *
 * Shaped so every construct in the query language has something to bite on —
 * multi-word names that need quoting, shared prefixes and suffixes for
 * wildcards, multi-valued fields for value-level booleans, integers, floats,
 * and ISO dates spread across every month of 2023 and 2024.
 */
export interface Produce {
  /** Catalog name. Multi-word names must be quoted or escaped in a query. */
  name: string;
  kind: "fruit" | "vegetable" | "grain" | "legume" | "nut" | "herb";
  /** Multi-valued: a filter matches when any element matches. */
  colors: string[];
  origin: string;
  /** Kilocalories per 100g. */
  calories: number;
  /** Typical weight of one unit, in grams. */
  grams: number;
  /** Retail price per unit, in dollars. */
  price: number;
  /** Seeds in one unit. */
  seeds: number;
  /** Harvest date, `YYYY-MM-DD`. */
  harvested: string;
  /** Multi-valued: a filter matches when any element matches. */
  tags: string[];
}

export const PRODUCE: Produce[] = [
  {
    name: "apple",
    kind: "fruit",
    colors: ["red", "green"],
    origin: "usa",
    calories: 52,
    grams: 182,
    price: 0.85,
    seeds: 10,
    harvested: "2023-09-14",
    tags: ["orchard", "seasonal"],
  },
  {
    name: "granny smith",
    kind: "fruit",
    colors: ["green"],
    origin: "australia",
    calories: 58,
    grams: 175.5,
    price: 1.1,
    seeds: 8,
    harvested: "2024-03-22",
    tags: ["orchard", "tart"],
  },
  {
    name: "banana",
    kind: "fruit",
    colors: ["yellow"],
    origin: "ecuador",
    calories: 89,
    grams: 118.25,
    price: 0.3,
    seeds: 0,
    harvested: "2024-01-08",
    tags: ["tropical", "imported"],
  },
  {
    name: "blueberry",
    kind: "fruit",
    colors: ["blue", "purple"],
    origin: "canada",
    calories: 57,
    grams: 1.5,
    price: 4.2,
    seeds: 55,
    harvested: "2023-07-19",
    tags: ["berry", "organic", "seasonal"],
  },
  {
    name: "strawberry",
    kind: "fruit",
    colors: ["red"],
    origin: "spain",
    calories: 32,
    grams: 12.4,
    price: 3.5,
    seeds: 200,
    harvested: "2024-05-11",
    tags: ["berry", "seasonal"],
  },
  {
    name: "raspberry",
    kind: "fruit",
    colors: ["red", "pink"],
    origin: "poland",
    calories: 52,
    grams: 3.75,
    price: 5.1,
    seeds: 120,
    harvested: "2023-08-02",
    tags: ["berry", "seasonal", "organic"],
  },
  {
    name: "blackberry",
    kind: "fruit",
    colors: ["black", "purple"],
    origin: "mexico",
    calories: 43,
    grams: 4.5,
    price: 4.75,
    seeds: 95,
    harvested: "2024-08-27",
    tags: ["berry"],
  },
  {
    name: "elderberry",
    kind: "fruit",
    colors: ["purple", "black"],
    origin: "germany",
    calories: 73,
    grams: 0.55,
    price: 6.4,
    seeds: 3,
    harvested: "2023-09-30",
    tags: ["berry", "medicinal"],
  },
  {
    name: "cranberry",
    kind: "fruit",
    colors: ["red"],
    origin: "usa",
    calories: 46,
    grams: 1.2,
    price: 3.95,
    seeds: 12,
    harvested: "2024-10-05",
    tags: ["berry", "tart", "seasonal"],
  },
  {
    name: "dragon fruit",
    kind: "fruit",
    colors: ["pink", "white"],
    origin: "vietnam",
    calories: 60,
    grams: 450,
    price: 7.25,
    seeds: 800,
    harvested: "2024-07-16",
    tags: ["tropical", "exotic"],
  },
  {
    name: "star fruit",
    kind: "fruit",
    colors: ["yellow", "green"],
    origin: "taiwan",
    calories: 31,
    grams: 91.5,
    price: 5.6,
    seeds: 14,
    harvested: "2023-11-21",
    tags: ["tropical", "exotic"],
  },
  {
    name: "mango",
    kind: "fruit",
    colors: ["orange", "red", "green"],
    origin: "india",
    calories: 60,
    grams: 336.75,
    price: 2.4,
    seeds: 1,
    harvested: "2024-06-04",
    tags: ["tropical", "organic"],
  },
  {
    name: "papaya",
    kind: "fruit",
    colors: ["orange", "green"],
    origin: "brazil",
    calories: 43,
    grams: 1200.5,
    price: 3.1,
    seeds: 350,
    harvested: "2023-04-18",
    tags: ["tropical"],
  },
  {
    name: "pineapple",
    kind: "fruit",
    colors: ["yellow", "brown"],
    origin: "costa rica",
    calories: 50,
    grams: 1500,
    price: 2.95,
    seeds: 0,
    harvested: "2024-02-13",
    tags: ["tropical"],
  },
  {
    name: "watermelon",
    kind: "fruit",
    colors: ["green", "red"],
    origin: "turkey",
    calories: 30,
    grams: 2500,
    price: 4.5,
    seeds: 400,
    harvested: "2023-07-28",
    tags: ["melon", "seasonal"],
  },
  {
    name: "cantaloupe",
    kind: "fruit",
    colors: ["orange", "tan"],
    origin: "usa",
    calories: 34,
    grams: 1350.25,
    price: 3.25,
    seeds: 300,
    harvested: "2024-08-09",
    tags: ["melon", "seasonal"],
  },
  {
    name: "orange",
    kind: "fruit",
    colors: ["orange"],
    origin: "spain",
    calories: 47,
    grams: 131,
    price: 0.75,
    seeds: 6,
    harvested: "2024-01-26",
    tags: ["citrus", "seasonal"],
  },
  {
    name: "lemon",
    kind: "fruit",
    colors: ["yellow"],
    origin: "italy",
    calories: 29,
    grams: 84.5,
    price: 0.6,
    seeds: 8,
    harvested: "2023-12-03",
    tags: ["citrus"],
  },
  {
    name: "lime",
    kind: "fruit",
    colors: ["green"],
    origin: "mexico",
    calories: 30,
    grams: 67.25,
    price: 0.45,
    seeds: 5,
    harvested: "2024-04-07",
    tags: ["citrus"],
  },
  {
    name: "grapefruit",
    kind: "fruit",
    colors: ["pink", "yellow"],
    origin: "usa",
    calories: 42,
    grams: 246,
    price: 1.35,
    seeds: 10,
    harvested: "2023-01-15",
    tags: ["citrus", "tart"],
  },
  {
    name: "mandarin",
    kind: "fruit",
    colors: ["orange"],
    origin: "china",
    calories: 53,
    grams: 88,
    price: 0.95,
    seeds: 4,
    harvested: "2023-12-19",
    tags: ["citrus", "seasonal"],
  },
  {
    name: "peach",
    kind: "fruit",
    colors: ["orange", "pink"],
    origin: "greece",
    calories: 39,
    grams: 150,
    price: 1.2,
    seeds: 1,
    harvested: "2024-07-02",
    tags: ["stone", "seasonal"],
  },
  {
    name: "pear",
    kind: "fruit",
    colors: ["green", "yellow"],
    origin: "belgium",
    calories: 57,
    grams: 178,
    price: 1.05,
    seeds: 9,
    harvested: "2023-10-11",
    tags: ["orchard"],
  },
  {
    name: "plum",
    kind: "fruit",
    colors: ["purple", "red"],
    origin: "serbia",
    calories: 46,
    grams: 66.5,
    price: 1.45,
    seeds: 1,
    harvested: "2024-09-01",
    tags: ["stone", "orchard"],
  },
  {
    name: "cherry",
    kind: "fruit",
    colors: ["red"],
    origin: "chile",
    calories: 63,
    grams: 8.25,
    price: 8.9,
    seeds: 1,
    harvested: "2023-06-22",
    tags: ["stone", "orchard"],
  },
  {
    name: "apricot",
    kind: "fruit",
    colors: ["orange"],
    origin: "turkey",
    calories: 48,
    grams: 35,
    price: 2.1,
    seeds: 1,
    harvested: "2024-06-25",
    tags: ["stone"],
  },
  {
    name: "fig",
    kind: "fruit",
    colors: ["purple", "green"],
    origin: "portugal",
    calories: 74,
    grams: 50,
    price: 6.75,
    seeds: 500,
    harvested: "2023-08-15",
    tags: ["orchard"],
  },
  {
    name: "kiwi",
    kind: "fruit",
    colors: ["green", "brown"],
    origin: "new zealand",
    calories: 61,
    grams: 69,
    price: 1.8,
    seeds: 600,
    harvested: "2024-11-12",
    tags: ["tropical", "imported"],
  },
  {
    name: "grape",
    kind: "fruit",
    colors: ["green", "purple"],
    origin: "italy",
    calories: 69,
    grams: 5,
    price: 2.65,
    seeds: 2,
    harvested: "2023-09-05",
    tags: ["vine", "seasonal"],
  },
  {
    name: "pomegranate",
    kind: "fruit",
    colors: ["red"],
    origin: "iran",
    calories: 83,
    grams: 282,
    price: 3.85,
    seeds: 613,
    harvested: "2024-10-23",
    tags: ["exotic"],
  },
  {
    name: "avocado",
    kind: "fruit",
    colors: ["green", "black"],
    origin: "peru",
    calories: 160,
    grams: 201,
    price: 2.2,
    seeds: 1,
    harvested: "2024-03-04",
    tags: ["tropical", "organic"],
  },
  {
    name: "tomato",
    kind: "fruit",
    colors: ["red"],
    origin: "netherlands",
    calories: 18,
    grams: 123,
    price: 1.15,
    seeds: 150,
    harvested: "2023-05-27",
    tags: ["vine", "greenhouse"],
  },
  {
    name: "carrot",
    kind: "vegetable",
    colors: ["orange"],
    origin: "netherlands",
    calories: 41,
    grams: 61,
    price: 0.55,
    seeds: 0,
    harvested: "2023-10-29",
    tags: ["root", "organic"],
  },
  {
    name: "sweet potato",
    kind: "vegetable",
    colors: ["orange", "purple"],
    origin: "usa",
    calories: 86,
    grams: 130.5,
    price: 0.9,
    seeds: 0,
    harvested: "2024-11-06",
    tags: ["root", "seasonal"],
  },
  {
    name: "potato",
    kind: "vegetable",
    colors: ["brown", "yellow"],
    origin: "ireland",
    calories: 77,
    grams: 213,
    price: 0.4,
    seeds: 0,
    harvested: "2023-08-21",
    tags: ["root", "staple"],
  },
  {
    name: "parsnip",
    kind: "vegetable",
    colors: ["cream"],
    origin: "england",
    calories: 75,
    grams: 92.75,
    price: 1.25,
    seeds: 0,
    harvested: "2024-12-02",
    tags: ["root", "seasonal"],
  },
  {
    name: "beetroot",
    kind: "vegetable",
    colors: ["purple", "red"],
    origin: "poland",
    calories: 43,
    grams: 82,
    price: 0.95,
    seeds: 0,
    harvested: "2023-11-08",
    tags: ["root", "organic"],
  },
  {
    name: "radish",
    kind: "vegetable",
    colors: ["red", "white"],
    origin: "japan",
    calories: 16,
    grams: 4.5,
    price: 1.1,
    seeds: 0,
    harvested: "2024-04-19",
    tags: ["root"],
  },
  {
    name: "turnip",
    kind: "vegetable",
    colors: ["white", "purple"],
    origin: "scotland",
    calories: 28,
    grams: 122,
    price: 0.85,
    seeds: 0,
    harvested: "2023-12-27",
    tags: ["root"],
  },
  {
    name: "kale",
    kind: "vegetable",
    colors: ["green"],
    origin: "scotland",
    calories: 49,
    grams: 16.25,
    price: 2.3,
    seeds: 0,
    harvested: "2024-01-17",
    tags: ["leafy", "organic"],
  },
  {
    name: "spinach",
    kind: "vegetable",
    colors: ["green"],
    origin: "italy",
    calories: 23,
    grams: 2.5,
    price: 2.75,
    seeds: 0,
    harvested: "2024-02-28",
    tags: ["leafy", "organic"],
  },
  {
    name: "romaine lettuce",
    kind: "vegetable",
    colors: ["green"],
    origin: "usa",
    calories: 17,
    grams: 310,
    price: 1.95,
    seeds: 0,
    harvested: "2023-05-09",
    tags: ["leafy"],
  },
  {
    name: "watercress",
    kind: "vegetable",
    colors: ["green"],
    origin: "england",
    calories: 11,
    grams: 0.85,
    price: 3.4,
    seeds: 0,
    harvested: "2024-03-15",
    tags: ["leafy", "organic"],
  },
  {
    name: "cabbage",
    kind: "vegetable",
    colors: ["green", "purple"],
    origin: "germany",
    calories: 25,
    grams: 900,
    price: 1.3,
    seeds: 0,
    harvested: "2023-10-02",
    tags: ["leafy", "staple"],
  },
  {
    name: "brussels sprout",
    kind: "vegetable",
    colors: ["green"],
    origin: "belgium",
    calories: 43,
    grams: 19.5,
    price: 2.85,
    seeds: 0,
    harvested: "2024-12-14",
    tags: ["seasonal"],
  },
  {
    name: "broccoli",
    kind: "vegetable",
    colors: ["green"],
    origin: "spain",
    calories: 34,
    grams: 608,
    price: 1.75,
    seeds: 0,
    harvested: "2023-03-11",
    tags: ["organic"],
  },
  {
    name: "cauliflower",
    kind: "vegetable",
    colors: ["white"],
    origin: "france",
    calories: 25,
    grams: 588,
    price: 2.05,
    seeds: 0,
    harvested: "2024-02-06",
    tags: ["seasonal"],
  },
  {
    name: "butternut squash",
    kind: "vegetable",
    colors: ["orange", "tan"],
    origin: "australia",
    calories: 45,
    grams: 1100,
    price: 1.65,
    seeds: 250,
    harvested: "2023-09-23",
    tags: ["squash", "seasonal"],
  },
  {
    name: "zucchini",
    kind: "vegetable",
    colors: ["green"],
    origin: "italy",
    calories: 17,
    grams: 196,
    price: 1.4,
    seeds: 40,
    harvested: "2024-07-24",
    tags: ["squash"],
  },
  {
    name: "cucumber",
    kind: "vegetable",
    colors: ["green"],
    origin: "netherlands",
    calories: 15,
    grams: 301,
    price: 0.8,
    seeds: 180,
    harvested: "2023-06-13",
    tags: ["greenhouse"],
  },
  {
    name: "bell pepper red",
    kind: "vegetable",
    colors: ["red"],
    origin: "netherlands",
    calories: 31,
    grams: 119,
    price: 1.9,
    seeds: 120,
    harvested: "2024-08-18",
    tags: ["greenhouse"],
  },
  {
    name: "bell pepper green",
    kind: "vegetable",
    colors: ["green"],
    origin: "spain",
    calories: 20,
    grams: 119,
    price: 1.5,
    seeds: 110,
    harvested: "2023-07-06",
    tags: ["greenhouse"],
  },
  {
    name: "bell pepper yellow",
    kind: "vegetable",
    colors: ["yellow"],
    origin: "israel",
    calories: 27,
    grams: 186,
    price: 2.15,
    seeds: 130,
    harvested: "2024-09-27",
    tags: ["greenhouse"],
  },
  {
    name: "pearl onion",
    kind: "vegetable",
    colors: ["white", "cream"],
    origin: "france",
    calories: 40,
    grams: 10.5,
    price: 2.45,
    seeds: 0,
    harvested: "2023-02-21",
    tags: ["allium"],
  },
  {
    name: "leek",
    kind: "vegetable",
    colors: ["green", "white"],
    origin: "wales",
    calories: 61,
    grams: 89,
    price: 1.85,
    seeds: 0,
    harvested: "2024-01-31",
    tags: ["allium", "seasonal"],
  },
  {
    name: "garlic",
    kind: "vegetable",
    colors: ["white"],
    origin: "china",
    calories: 149,
    grams: 3,
    price: 1.2,
    seeds: 0,
    harvested: "2023-07-14",
    tags: ["allium", "staple"],
  },
  {
    name: "asparagus",
    kind: "vegetable",
    colors: ["green", "purple"],
    origin: "peru",
    calories: 20,
    grams: 12.5,
    price: 4.95,
    seeds: 0,
    harvested: "2024-05-02",
    tags: ["seasonal"],
  },
  {
    name: "quinoa",
    kind: "grain",
    colors: ["tan", "white"],
    origin: "bolivia",
    calories: 368,
    grams: 0.01,
    price: 5.25,
    seeds: 1,
    harvested: "2023-04-26",
    tags: ["staple", "organic"],
  },
  {
    name: "barley",
    kind: "grain",
    colors: ["tan"],
    origin: "canada",
    calories: 354,
    grams: 0.04,
    price: 1.1,
    seeds: 1,
    harvested: "2024-06-14",
    tags: ["staple"],
  },
  {
    name: "brown rice",
    kind: "grain",
    colors: ["brown"],
    origin: "thailand",
    calories: 370,
    grams: 0.02,
    price: 2.35,
    seeds: 1,
    harvested: "2023-11-02",
    tags: ["staple"],
  },
  {
    name: "rolled oats",
    kind: "grain",
    colors: ["cream"],
    origin: "finland",
    calories: 389,
    grams: 0.03,
    price: 1.75,
    seeds: 1,
    harvested: "2024-04-11",
    tags: ["staple", "organic"],
  },
  {
    name: "rye",
    kind: "grain",
    colors: ["tan", "brown"],
    origin: "poland",
    calories: 338,
    grams: 0.03,
    price: 1.55,
    seeds: 1,
    harvested: "2023-08-29",
    tags: ["staple"],
  },
  {
    name: "sweet corn",
    kind: "grain",
    colors: ["yellow"],
    origin: "usa",
    calories: 86,
    grams: 154,
    price: 0.7,
    seeds: 800,
    harvested: "2024-08-05",
    tags: ["staple", "seasonal"],
  },
  {
    name: "pea",
    kind: "legume",
    colors: ["green"],
    origin: "england",
    calories: 81,
    grams: 0.35,
    price: 2.6,
    seeds: 1,
    harvested: "2023-06-05",
    tags: ["organic", "seasonal"],
  },
  {
    name: "chickpea",
    kind: "legume",
    colors: ["tan"],
    origin: "india",
    calories: 364,
    grams: 0.45,
    price: 1.95,
    seeds: 1,
    harvested: "2024-10-14",
    tags: ["staple", "organic"],
  },
  {
    name: "red lentil",
    kind: "legume",
    colors: ["red", "orange"],
    origin: "turkey",
    calories: 358,
    grams: 0.05,
    price: 1.85,
    seeds: 1,
    harvested: "2023-03-27",
    tags: ["staple"],
  },
  {
    name: "black bean",
    kind: "legume",
    colors: ["black"],
    origin: "brazil",
    calories: 341,
    grams: 0.55,
    price: 1.65,
    seeds: 1,
    harvested: "2024-11-25",
    tags: ["staple"],
  },
  {
    name: "edamame",
    kind: "legume",
    colors: ["green"],
    origin: "japan",
    calories: 121,
    grams: 0.65,
    price: 3.75,
    seeds: 1,
    harvested: "2023-09-11",
    tags: ["organic"],
  },
  {
    name: "green bean",
    kind: "legume",
    colors: ["green"],
    origin: "kenya",
    calories: 31,
    grams: 6.5,
    price: 2.9,
    seeds: 6,
    harvested: "2024-05-20",
    tags: ["seasonal"],
  },
  {
    name: "almond",
    kind: "nut",
    colors: ["brown", "tan"],
    origin: "usa",
    calories: 579,
    grams: 1.2,
    price: 9.5,
    seeds: 1,
    harvested: "2023-10-17",
    tags: ["snack", "organic"],
  },
  {
    name: "walnut",
    kind: "nut",
    colors: ["brown"],
    origin: "china",
    calories: 654,
    grams: 8.5,
    price: 8.75,
    seeds: 1,
    harvested: "2024-10-08",
    tags: ["snack"],
  },
  {
    name: "peanut",
    kind: "nut",
    colors: ["brown", "tan"],
    origin: "argentina",
    calories: 567,
    grams: 0.85,
    price: 3.2,
    seeds: 1,
    harvested: "2023-05-16",
    tags: ["snack", "staple"],
  },
  {
    name: "pistachio",
    kind: "nut",
    colors: ["green", "purple"],
    origin: "iran",
    calories: 560,
    grams: 0.7,
    price: 14.5,
    seeds: 1,
    harvested: "2024-09-12",
    tags: ["snack"],
  },
  {
    name: "hazelnut",
    kind: "nut",
    colors: ["brown"],
    origin: "turkey",
    calories: 628,
    grams: 2,
    price: 11.25,
    seeds: 1,
    harvested: "2023-11-27",
    tags: ["snack", "organic"],
  },
  {
    name: "cashew",
    kind: "nut",
    colors: ["cream"],
    origin: "vietnam",
    calories: 553,
    grams: 1.6,
    price: 12.8,
    seeds: 1,
    harvested: "2024-03-29",
    tags: ["snack", "imported"],
  },
  {
    name: "basil",
    kind: "herb",
    colors: ["green"],
    origin: "italy",
    calories: 23,
    grams: 0.45,
    price: 2.5,
    seeds: 0,
    harvested: "2024-06-19",
    tags: ["leafy", "organic"],
  },
  {
    name: "rosemary",
    kind: "herb",
    colors: ["green"],
    origin: "greece",
    calories: 131,
    grams: 0.3,
    price: 2.2,
    seeds: 0,
    harvested: "2023-02-07",
    tags: ["aromatic"],
  },
  {
    name: "mint",
    kind: "herb",
    colors: ["green"],
    origin: "morocco",
    calories: 70,
    grams: 0.25,
    price: 1.95,
    seeds: 0,
    harvested: "2024-05-27",
    tags: ["aromatic", "organic"],
  },
  {
    name: "cilantro",
    kind: "herb",
    colors: ["green"],
    origin: "mexico",
    calories: 23,
    grams: 0.2,
    price: 1.4,
    seeds: 0,
    harvested: "2023-04-03",
    tags: ["leafy"],
  },
  {
    name: "thyme",
    kind: "herb",
    colors: ["green"],
    origin: "france",
    calories: 101,
    grams: 0.05,
    price: 2.65,
    seeds: 0,
    harvested: "2024-02-20",
    tags: ["aromatic"],
  },
  {
    name: "saffron",
    kind: "herb",
    colors: ["red", "orange"],
    origin: "iran",
    calories: 310,
    grams: 0.01,
    price: 45,
    seeds: 0,
    harvested: "2023-10-24",
    tags: ["aromatic", "exotic"],
  },
  {
    name: "parsley",
    kind: "herb",
    colors: ["green"],
    origin: "israel",
    calories: 36,
    grams: 0.35,
    price: 1.3,
    seeds: 0,
    harvested: "2024-04-02",
    tags: ["leafy"],
  },
];
